version: '3.7'

services:
  db:
    image: postgres:13.3
    container_name: db
    ports:
      - 5433:5432
    env_file:
      - ./secrets/db-production.env
    volumes:
      - db-data:/val/lib/postgresql/data

  app:
    image: openjdk:21-jdk
    container_name: app
    working_dir: /data
    ports:
      - 8080:8080
    volumes:
      - ./target/yandexTaxi-0.0.1-SNAPSHOT.jar:/data/app.jar
    command: [ "java", "-jar", "./app.jar" ]
    restart: always
    env_file:
      - ./secrets/app-production.env

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./infra/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./infra/grafana/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  db-data:
