yandex:
  url: https://taxi-routeinfo.taxi.yandex.net/taxi_info
  clid: ${YANDEX_CLID}
  apiKey: ${YANDEX_APIKEY}

coordinate:
  start-longitude: 30.31714
  start-latitude: 59.93965
  finish-longitude: 30.24898
  finish-latitude: 59.84947

management:
  info:
    os:
      enabled: true
    java:
      enabled: true
  metrics:
    enable:
      tomcat: true
      jvm: true
      process: true
      hikaricp: true
      system: true
      jdbc: true
      logback: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      slo:
        http.server.requests: 1ms, 10ms, 50ms
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,features
  prometheus:
    metrics:
      export:
        enabled: true
