{
 "title": "yandex prices dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Цена такси",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "priceTaxi", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Максимальное время выполнение планировщика",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "schedulerTaxi_seconds_max", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Время получение цены от яндекса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(gettingPriceFromYandex_seconds_sum [1m]) / increase(gettingPriceFromYandex_seconds_count [1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время получения всех цен из БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "increase(schedulerTaxi_seconds_sum[1m])/increase(schedulerTaxi_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}